name: climate-downscaling
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - kornia
  - lightning
  - numpy
  - python=3.10
  - pytorch
  - scikit-image
  - tensorboard
  - torchmetrics
  - torchvision
  - tqdm
  